name: ASP.NET CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: [self-hosted, Windows]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test

    - name: Publish
      run: dotnet publish -c Release -o D:\Published\CICDAPI


  deploy:
    needs: build
    runs-on: [self-hosted, Windows]

    steps:

    # 🔥 STEP 1: STOP IIS (IMPORTANT - FIX LOCK ISSUE)
    - name: Stop IIS App Pool
      run: |
        Import-Module WebAdministration
        Stop-WebAppPool -Name "TestingCICD"

    # 🔥 STEP 2: CLEAN DEPLOY FOLDER
    - name: Clean Deploy Folder
      run: |
        Remove-Item -Recurse -Force D:\Deploy\TestingCICD -ErrorAction SilentlyContinue
        New-Item -ItemType Directory -Force -Path D:\Deploy\TestingCICD

    # 🔥 STEP 3: DEPLOY FILES
    - name: Deploy Files
      run: robocopy D:\Published\CICDAPI D:\Deploy\TestingCICD /MIR /R:2 /W:2

    # 🔥 STEP 4: START IIS AGAIN
    - name: Start IIS App Pool
      run: |
        Import-Module WebAdministration
        Start-WebAppPool -Name "TestingCICD"
